### ISSUE TITLE
Easiest way to create new assets ?

### ISSUE THREAD

**Issue by RobinLbt** [cryptopunksnotdead/awesome-24px#1]
Love your work !

I was wondering which software do you use to create new assets and have a perfect alignment for every combination, it seems very hard to do manually using Photoshop

**Comment by geraldb** [comment]
@RobinLbt  Love your question - please repost to the public forum - <https://old.reddit.com/r/DIYPunkArt/>   - I am happy to answer / chime in over there  - the idea is to keep all support questions / discussion in one forum (instead of dozens of github/repos/orgs)  - thanks for your understanding.
